#!/usr/bin/env python3
"""Build pipeline-data.js from 'Pipeline system team.xlsx' (sheet Pipeline2026).

Normalizes the messy source data:
- Team: ENT/Ent/ENTE -> ENT, Mtis -> MTIS (uppercase everything)
- Status: win/Win -> Win, lost/Lost -> Lost, drop/Drop -> Drop, Inprogress -> In Progress
- Quarters: strips stray Thai chars (e.g. 'Q2/202\u0e366' -> 'Q2/2026'), validates Q1-4
- Revenue / %progress / %win: coerced to numbers, clamped 0-100 for percents
- Start Date: real dates -> ISO, junk strings ('16/4/20206') -> null

Usage: py build_data.py ["Pipeline system team.xlsx"] [pipeline-data.js]
"""
import json
import re
import sys
from datetime import date, datetime

from openpyxl import load_workbook

SRC = sys.argv[1] if len(sys.argv) > 1 else "Pipeline system team.xlsx"
OUT = sys.argv[2] if len(sys.argv) > 2 else "pipeline-data.js"

TEAM_MAP = {"ENTE": "ENT", "ENT": "ENT", "MTIS": "MTIS", "BFSI": "BFSI",
            "GOV": "GOV", "TELCO": "TELCO", "INNO": "INNO"}


def clean(s):
    if s is None:
        return None
    t = str(s).replace("\xa0", " ").strip()
    return t if t else None


def norm_team(s):
    t = clean(s)
    if not t:
        return None
    u = re.sub(r"\s+", " ", t.upper())
    return TEAM_MAP.get(u, u)


def norm_status(s):
    t = clean(s)
    if not t:
        return "In Progress"
    low = t.lower()
    if "win" in low:
        return "Win"
    if "lost" in low or "lose" in low:
        return "Lost"
    if "drop" in low:
        return "Drop"
    return "In Progress"


def parse_quarter(s):
    t = clean(s)
    if not t:
        return None
    t = re.sub(r"[^\x00-\x7f]", "", t)  # strip stray Thai chars (typos)
    m = re.search(r"[qQ]\s*(\d)\s*/\s*(\d{4})", t)
    if m:
        q, y = int(m.group(1)), int(m.group(2))
        if 1 <= q <= 4 and 2000 <= y <= 2100:
            return f"Q{q}/{y}"
    return t or None


def num(v):
    if v is None:
        return None
    if isinstance(v, (int, float)):
        return float(v)
    t = re.sub(r"[^\d.\-]", "", str(v))
    if not t:
        return None
    try:
        return float(t)
    except ValueError:
        return None


def pct(v, default):
    n = num(v)
    if n is None:
        return default
    return int(max(0, min(100, round(n))))


def parse_date(v):
    if isinstance(v, datetime):
        return v.date().isoformat()
    if isinstance(v, date):
        return v.isoformat()
    return None  # junk strings like '16/4/20206'


def main():
    wb = load_workbook(SRC, data_only=True)
    ws = wb["Pipeline2026"]

    projects = []
    stats = {"rows": 0, "no_status": 0, "no_revenue": 0, "no_target": 0}
    for i, r in enumerate(range(2, ws.max_row + 1), start=1):
        team = norm_team(ws.cell(r, 1).value)
        name = clean(ws.cell(r, 9).value)
        customer = clean(ws.cell(r, 5).value)
        if not any([team, name, customer]):
            continue
        stats["rows"] += 1
        if not clean(ws.cell(r, 15).value):
            stats["no_status"] += 1
        revenue = num(ws.cell(r, 10).value)
        if revenue is None:
            stats["no_revenue"] += 1
        target = parse_quarter(ws.cell(r, 7).value)
        if target is None:
            stats["no_target"] += 1
        projects.append({
            "id": f"P{i:03d}",
            "team": team,
            "code": clean(ws.cell(r, 2).value),
            "sales": clean(ws.cell(r, 3).value),
            "presales": clean(ws.cell(r, 4).value),
            "customer": customer,
            "start": parse_quarter(ws.cell(r, 6).value),
            "target": target,
            "startDate": parse_date(ws.cell(r, 8).value),
            "name": name,
            "revenue": revenue,
            "product": clean(ws.cell(r, 11).value),
            "register": clean(ws.cell(r, 12).value),
            "progressPct": pct(ws.cell(r, 13).value, 0),
            "winPct": pct(ws.cell(r, 14).value, 50),
            "status": norm_status(ws.cell(r, 15).value),
            "statusNote": clean(ws.cell(r, 16).value),
            "action": clean(ws.cell(r, 17).value),
        })

    seed = {
        "generatedAt": datetime.now().isoformat(timespec="seconds"),
        "sourceFile": SRC,
        "projects": projects,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by build_data.py from %s - do not edit by hand\n" % SRC)
        f.write("window.PIPELINE_SEED = %s;\n" % json.dumps(seed, ensure_ascii=False))

    teams = {}
    for p in projects:
        teams[p["team"]] = teams.get(p["team"], 0) + 1
    print(json.dumps({"out": OUT, **stats, "teams": teams},
                     ensure_ascii=False, indent=1))


if __name__ == "__main__":
    main()
